package xjunz.tool.mycard.monitor

/**
 * @author xjunz 2022/3/2
 */
object State {

    const val CONNECTING = 0x10

    const val CONNECTED = 0x20

    /* DISCONNECTED: NEUTRAL STATES */
    const val DISCONNECTED_IDLE = 0x30
    const val DISCONNECTED_USER_REQUEST = 0x31

    /* DISCONNECTED: ERROR STATES */
    const val DISCONNECTED_TIMED_OUT = 0x36
    const val DISCONNECTED_NETWORK = 0x37
    const val DISCONNECTED_SERVER = 0x38
    const val DISCONNECTED_REJECTED = 0x39
    const val DISCONNECTED_UNEXPECTED = 0x3F

    val DISCONNECTED = DISCONNECTED_IDLE..DISCONNECTED_UNEXPECTED

    val DISCONNECTED_ERROR = DISCONNECTED_TIMED_OUT..DISCONNECTED_UNEXPECTED

    val DISCONNECTED_NEUTRAL = DISCONNECTED_IDLE..DISCONNECTED_USER_REQUEST
}